version: '3.5'

services:
  php:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/app
      - ./vendor:/var/www/app/vendor
    environment:
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_DISCOVER_CLIENT_HOST=false

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - php