version: '3.5'

services:
  php:
    container_name: php
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080
      - 8000:8000
    working_dir: /var/www/app
    image: php:8.2-fpm
    volumes:
      - .:/var/www/app
      - ./vendor:/var/www/app/vendor
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_DISCOVER_CLIENT_HOST=false

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8001:80'
    depends_on:
      - php